### PR TITLE
Update to support PHP 8. Bump PHP 7.2 to 7.4.

### PR DESCRIPTION
**Pull request by Colbydude**
Hello,

This PR adds support for PHP 8 and bumps the required minimum PHP 7 version to 7.4, since 7.2 is no longer even in security support.

Let me know if you have questions!

### CODE REVIEW

**Comment by bredmor** [comment]
Can confirm this appears to work. There's no test suite to run, but every request I've made seems to go through just fine.

**Comment by PiousVenom** [comment]
Can we get a release created for this update? The last release was in 2019.

**Comment by Supamiu** [comment]
We're not using releases anymore, because prod env is just sync'd with last commit on master, making it easier to push changes without having to create a release for each change we want to push, as updating prod env is nothing more than just `git pull` on the prod server.

**Comment by PiousVenom** [comment]
I'm not sure I follow. If I try to follow the readme and do a composer require, I get an old 2019 release. How would I be able to get the latest code to use if no releases are generated? Could the documentation be updated to show this?

**Comment by bredmor** [comment]
Hi @PiousVenom, if you want the latest branch with PHP 7.4|8.0 support, you'd want to specify `dev-master` as your package version when installing, or edit your composer.json to specify such.

i.e. `composer require xivapi/xivapi-php dev-master`

**Pull request merged**
